version: '3.4'

services:
  kanban:
    image: shortpoet/kanban
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    env_file:
      - 'docker.env'
    environment:
      NODE_ENV: production
    ports:
      # - 3000
      - 4000:4000
      - 5000:5000
      # - 8080
    volumes:
      - .:/usr/src/app
    networks:
      - kanbannet
    command: yarn start:rest
    entrypoint: ./docker-entrypoint.sh
  
  # https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945
  db:
    image: postgres:12
    # restart: always
    restart: unless-stopped
    # file must end in .sql not .psql
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql:ro
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - 'docker.env'
    ports:
      - 5432:5432
    networks:
      - kanbannet

networks:
  kanbannet:

volumes:
  postgres-data: